
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RpkzgdhUnGH
 */
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient()

export async function Guest_details() {

const data = await prisma.guests.findMany({
  include:{
    Bookings:{
      orderBy: {
        Check_in: 'desc', // Sort by Check_in date in descending order
      },
      take: 1, // Take only the first result
      select:{
        Room_type:true,
        Check_in:true,
        Special_request:true,
         }
    }
  }
});
return JSON.stringify(data);
//   return (
//  <div className="bg-white shadow rounded-lg">
//        {data && (
//       <div className="overflow-x-auto">
//         <Table>
//           <TableHeader>
//             <TableRow>
//               <TableHead>Name</TableHead>
//               <TableHead>City</TableHead>
//               <TableHead>Room Type</TableHead>
//               <TableHead>Special Requests</TableHead>
//               <TableHead>Last Visited On</TableHead>
//               <TableHead>Type of ID</TableHead>
//               <TableHead>Guest ID</TableHead>
//               <TableHead className="w-[50px]" />
//             </TableRow>
//           </TableHeader>
//           <TableBody>
//             {data.map((guest, index) => (
//               <TableRow key={index}>
//                 <TableCell>{guest.First_name} {guest.Last_name}</TableCell>
//                 <TableCell>{guest.City}</TableCell>
//                 <TableCell>{guest.Bookings[0] ? guest.Bookings[0].Room_type : '-'}</TableCell>
//                 <TableCell>{guest.Bookings[0] ? guest.Bookings[0].Special_request : '-'}</TableCell>
//                 <TableCell>{guest.Bookings[0] ? new Date(guest.Bookings[0].Check_in).toLocaleString() : '-'}</TableCell>
//                 <TableCell>{guest.Type_of_id}</TableCell>
//                 <TableCell>{guest.Guest_id}</TableCell>
//               </TableRow>
//             ))}
//           </TableBody>
//         </Table>
//       </div>
//     )}
//       <Button className="fixed bottom-4 right-4 rounded-full bg-blue-600 text-white p-4 shadow-lg">
//         <PlusIcon className="text-white" />
//       </Button>
//     </div>
//   )
// }



// function PlusIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M5 12h14" />
//       <path d="M12 5v14" />
//     </svg>
//   )
}
